name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: git clone https://github.com/asdf-vm/asdf.git
      - run: . asdf/asdf.sh && asdf plugin add selleo https://github.com/selleo/asdf-cli.git
      - run: . asdf/asdf.sh && asdf install selleo latest
      - run: . asdf/asdf.sh && asdf global selleo latest
      - name: test
        run: . asdf/asdf.sh && selleo version